api:
  deployment:
    name: codestar-api
    replicaCount: 2
    containerPort: 8080
    image:
      name: ghcr.io/star-academy/summer1403-project-group02-backend
      pullPolicy: IfNotPresent
      tag: 0.8.2

    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi

    pullSecret:
      enabled: false
      name: api-ghcr-secret

  secret:
    enabled: false
    name: api-secret

  config:
    name: codestar-api-config
    asp_environment: Development

  service:
    name: codestar-api
    port: 80

  ingress:
    enabled: true
    ingressClassName: nginx
    name: codestar-api-ingress
    rules:
      - host: codestar-g2-api.abriment.com
        path: /
        pathType: Prefix

frontend:
  deployment:
    name: codestar-frontend
    replicaCount: 2
    containerPort: 80
    image:
      name: ghcr.io/star-academy/summer1403-project-group02-frontend
      pullPolicy: IfNotPresent
      tag: 0.3.0

    resources:
      limits:
        cpu: 400m
        memory: 800Mi
      requests:
        cpu: 200m
        memory: 400Mi

    pullSecret:
      enabled: false
      name: frontend-ghcr-secret

  service:
    name: codestar-frontend
    port: 80

  config:
    name: codestar-frontend-config
    nginx:
      worker_processes: 1

  ingress:
    enabled: true
    ingressClassName: nginx
    name: codestar-frontend-ingress
    rules:
      - host: codestar-g2.abriment.com
        path: /
        pathType: Prefix
